spring:
  velocity:
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8
    cache: false


server:
  port: 8080


mysql:
  enable: true
  url: "jdbc:mysql://192.168.1.26:3306/back_universal?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useAffectedRows=true&allowMultiQueries=true"
  driverClassName: "com.mysql.jdbc.Driver"
  username: "root"
  password: "root"
  initialSize: 5
  maxIdle: 10
  maxActive: 50
  validationQuery: "select 1"


redis:
  enable: true
  host: 192.168.1.26
  port: 6379
